### ISSUE TITLE
How to inject HTML into the template?

### ISSUE THREAD

**Issue by AndreiBadescu** [wojtekmaj/vite-plugin-simple-html#5]
From the docs I don't understand how to template my html.
Let's say I have a footer.html which I want to integrate in every html file from my project at the bottom of the body. How could I do this using this plugin?

**Comment by wojtekmaj** [comment]
Add EJS variable in your template.

```diff
<html>
  <head>
    <title>Hello world!</title>
  </head>
  <body>
+   <%= footer %>
  </body>
</html>
```

In Vite config, load HTML contents from anywhere, in your case, from your filesystem.

```ts
import fs from 'node:fs';

const footer = fs.readFileSync('/path/to/footer.html', 'utf-8');
```

In plugin config, inject the HTML contents into EJS variable.

```ts
  plugins: [
    simpleHtmlPlugin({
      minify: isProduction ? minifyOptions : false,
      inject: {
        data: {
          footer,
        },
      },
    }),
  ]
```
