### ISSUE TITLE
HTML minifier doesn't process generated asset elements

### ISSUE THREAD

**Issue by mataha** [wojtekmaj/vite-plugin-simple-html#6]
`vite.config.js`:

```js
import { defineConfig } from "vite";
import viteSimpleHtml from "vite-plugin-simple-html";

export default defineConfig({
    plugins: [
        viteSimpleHtml({
            minify: true,
        }),
    ],
});
```

`index.html`:

```html
<!DOCTYPE html>
<html lang="en-US" dir="ltr">
    <head>
        <link rel="stylesheet" type="text/css" href="./main.css" />
        <title>Sample Site</title>
    </head>
</html>
```

`vite build` - `dist/index.html`:

```html
<!doctype html><html lang="en-US" dir="ltr"><head><title>Sample Site</title>  <link rel="stylesheet" crossorigin href="/assets/index-MCPePPYg.css">
</head></html>
```

Notice the following:

- whitespace before the `<link>` element
- a newline after the `<link>` element

`html-minifier-terser`'s `collapseWhitespace` should take care of that, but it seems to run before assets get replaced. For reference:

```console
$ ./yarnw dlx html-minifier-terser --collapse-whitespace dist/index.html
<!doctype html><html lang="en-US" dir="ltr"><head><title>Sample Site</title><link rel="stylesheet" crossorigin href="/assets/index-MCPePPYg.css"></head></html>
```

**Comment by wojtekmaj** [comment]
Hmmmm... The reason vite-plugin-simple-html runs before assets are replaced is #1. Not sure yet how we could proceed here to satisfy both.

**Comment by mataha** [comment]
I'll pin the version used in my project to `0.1.0` while I think of a permanent solution...

**Comment by wojtekmaj** [comment]
We could do 2 passes: 
1st - adding variables
2nd - minifying

And let all the other stuff run in between 🤔

**Comment by mataha** [comment]
Thanks!
